### ISSUE TITLE
New USer ask..

### ISSUE THREAD

**Issue by FMDose89** [faucetbrowser/faucetbrowser#1]
Thank u Sir. Thank you very much for your hard work. It would be cool if there was a tutorial video how to work with all the codes from GitHub faucetbrowser. Regarding docker, for me personally as a "FULL NULL" user it's hard to understand these settings, even with step by step instructions... it's not clear what you're doing why you're doing it, what will happen to the PC, etc.

**Comment by faucetbrowser** [comment]
Hi,
Thank you for your feedback. 
There is nothing much to work with the code. You will have to follow the prerequisites to install the docker. For this you can search youtube videos on how to install docker. 
https://github.com/faucetbrowser/faucetbrowser#prerequisites 
Regarding your pc, the script comes with default limitation of 1 GB RAM and 1 CPU. That's the maximum limit set and it does not have access to other folders on your system. You can change that limit if you wish. It runs in an isolated environment.
You have to enter the wallet address as mentioned before starting the script. 
You can start with prerequisites and update where you have difficultly understanding. The documentation will be updated for that section. 

Thank you

**Comment by FMDose89** [comment]
Hard for me(

**Comment by faucetbrowser** [comment]
Hi,
Could you please let us know where you were stuck. Its one time setup only. 
If you have ubuntu OS, the steps are straight forward.  

Thank you
